### ISSUE TITLE
Workshop Title

### ISSUE THREAD

**Issue by dlab-frontdesk** [dlab-berkeley/R-Machine-Learning-Legacy#16]
Workshop title should be "R-Introduction-to-Machine-Learning-with-tidymodels"

**Comment by asteves** [comment]
@aculich Actually tagging you on purpose for this one to confirm that we are not fixing these issues. I've seen you make this comment on other repos.

**Comment by aculich** [comment]
The title listed above is not quite correct, but we do need to update the title on this and most other workshops— however that is something @pattyf and I will look at across all of our workshops, so we can close this and the other issues like it for now and we'll circle back to this later.
