### ISSUE TITLE
Error in Part 3 .rmd, Ensembles Section, cannot find fit_members() function 

### ISSUE THREAD

**Issue by joseaveldanes** [dlab-berkeley/R-Machine-Learning-Legacy#29]
On lines 381-389, R cannot find fit_members() function unless explicitly installing stacks package. We might need a section for this in the notebook.

**Comment by pssachdeva** [comment]
This may require the explicit installation of the `stacks` package.

**Comment by asteves** [comment]
This should now be fixed by the explicit loading of the stacks package so closing.
