### ISSUE TITLE
Error producing metrics and confusion plot

### ISSUE THREAD

**Issue by Akesari12** [dlab-berkeley/R-Machine-Learning-Legacy#4]
In lines 251-256 of [04-decision-trees.rmd](https://github.com/dlab-berkeley/Machine-Learning-with-tidymodels/blob/master/04-decision-trees.Rmd) these two plots run into errors. I think it's because tree_fit_viz_metr and tree_fit_viz_mat are not defined already. Here is the relevant code:

`# Metrics 
(tree_fit_viz_metr + labs(title = "Non-tuned")) / (visualize_class_eval(tree_fit_tuned) + labs(title = "Tuned"))

# Confusion matrix 
(tree_fit_viz_mat + labs(title = "Non-tuned")) / (visualize_class_conf(tree_fit_tuned) + labs(title = "Tuned"))`

**Comment by jaeyk** [comment]
Both objects should have been defined in the lines between 145-151. 

```{r}
tree_fit_viz_metr <- visualize_class_eval(tree_fit)

tree_fit_viz_metr

tree_fit_viz_mat <- visualize_class_conf(tree_fit)

tree_fit_viz_mat
```

Have you run `source(here("functions", "utils.R"))` in line 18? Both `visualize_class_eval()` and `visualize_class_conf()` are my custom functions and come from `utils.R` script. 

I tested the R markdown file on my laptop and it ran well.

**Comment by Akesari12** [comment]
Just refreshed and re-ran everything, and it all works! Sorry for the false alarm!
