### ISSUE TITLE
Clarify installation workflow

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/R-Machine-Learning-Legacy#42]
From the instructions it is unclear which step is suppose to be performed first:
1. The first line in Part1 `renv::init()`
2. The 5th step in installation instructions `install.packages(c("tidyverse", "tidymodels", "here","pROC","glmnet", "ranger", "rpart", "xgboost","rpart.plot", "doParallel", "palmerpenguins", "ISLR2", "klaR", "stacks"))`

**Comment by asteves** [comment]
@seanmperez We are still experimenting with what is going to be easier. The instructions on the README are what we'd like every learner to do right now. 

If the `renv::init()` makes more sense to learners, then we will transition to that. 

It's also done in Part1 to be a backup in case learners had not downloaded and installed packages ahead of time.
