### ISSUE TITLE
Add datahub and binder links and icons

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/R-Machine-Learning-Legacy#53]
@pssachdeva I just noticed this repo is missing binerhub links in the README: https://github.com/dlab-berkeley/R-Machine-Learning/blob/ee158d8506d68e72498a36d7484a403ed5b4b506/README.md?plain=1#L81-L87

Any chance you could add it and test it in time for today's workshop at 10am since we have folks from partner organizations who may need a binderized version?

Also, it would be great if you can add the iconified buttons like what's shown in [R Fundamentals](https://github.com/dlab-berkeley/R-Fundamentals):

<img width="864" alt="image" src="https://user-images.githubusercontent.com/118965/204600358-0fd3922e-4c99-4e99-9f4d-c0f4e3a7afdf.png">

Thanks!

**Comment by pssachdeva** [comment]
There's an icon at the top, but I'll add a button at the bottom later.

I wasn't able to get a Binder link working with this repo, and I haven't quite figured out why. At any rate, installing RStudio is much easier than Anaconda, so I feel pretty comfortable with people using a local install over a Binder link. I'll give it one more shot before the workshop starts.

**Comment by pssachdeva** [comment]
Closed by #61
