### ISSUE TITLE
Simplify and update renv package installation process

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/R-Machine-Learning-Legacy#54]
The `renv` can be simplified to remove unnecessary packages (to speed up (re-)installation) and replaced with an exact step-by-step process for people to follow. Some participants struggled with package installation as it is currently written.

https://github.com/dlab-berkeley/R-Machine-Learning/blob/ee158d8506d68e72498a36d7484a403ed5b4b506/README.md?plain=1#L43-L75

Also, `install_github()` should be replaced with standard `install.packages()` where possible, e.g. `remotes::install_github("tidymodels/discrim")` can just be `install.packages("discrim")` since the standard v1.0.0 package has been released now.

This caused additional issues because it assumes they have already run `install.packages("remotes")` because it is not explicitly stated in the instructions, so add that if there's a good reason to keep any `install_github` calls around.

**Comment by aculich** [comment]
A further confounding factor with one participant was that their `renv` was located in a Dropbox folder on a Windows system, so when `install_github` requires compiling a package it sometimes causes build failures (at least for this person).

So, if there is a troubleshooting FAQ, make sure to mention that if they encounter installation issues that they should make sure they're not in a Dropbox folder.

**Comment by pssachdeva** [comment]
Closed by #61
