### ISSUE TITLE
Hard stop errors when running .RMD(s) on my local environment. 

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/R-Machine-Learning-Legacy#6]
- [x] **Overview-1.RMD**
needed to:

`install.packages(‘rlang’)`

before installation of all packages chunk, or else ggplot2 would not load. 

- [x] **04- Decision Trees,** ln. 196
_Error in makePSOCKcluster(names = spec, ...) : Cluster setup failed. 4 of 4 workers failed to connect._

Error did not break the .RMD workflow. 

- [x] **05 - Random Forest**
`update_model()` function, same error as above

- [x] **06- xgboost**
`update_model()`, same error, ln. 351

- [x] **09 - hlclust**

ln. 37:
_Error: Problem with `mutate()` input `..1`. x there is no package called ‘BBmisc’ℹ Input `..1` is `across(is.numeric, BBmisc::normalize)`_

`install.packages("BBmisc")

`library(BBmisc)` 

and np. 

 
--

_

**Comment by jaeyk** [comment]
- [x] **Overview-1.RMD**
You need to update `rlang` first. `update.packges("rlang"). See [this exchange](https://community.rstudio.com/t/rlang-error-in-installing-in-ggplot2/20468).

- [x] **04- Decision Trees,** ln. 196, **05 - Random Forest**, **06- xgboost**
_Error in makePSOCKcluster(names = spec, ...) : Cluster setup failed. 4 of 4 workers failed to connect._

4 workers worked for me, but might not work for your laptop. Try the following:

```{r}
# Determine the number of cores
no_cores <- detectCores() - 1

# Initiate
cl <- makeCluster(no_cores)
```

- [x] **09 - hlclust**

Try the following:

```{r}
if (!require("pacman")) install.packages("pacman")

pacman::p_load(BBmisc)
```
 
--


_
